### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by harukaza** [nihirv/controllable-vqg#1]
how to get the file  _pred.coco_caption.val.beam5.max20.odlabels.tsv_ ?

**Comment by nihirv** [comment]
This is a while ago so I cannot recall 100%. I believe we used Oscar: https://github.com/microsoft/Oscar to generate the captions and their features.

I have the files on a server but they total ~130gb, which makes it infeasible for me to upload unfortunately. Let me know if Oscar does not work and we can see what else can be done

**Comment by harukaza** [comment]
Thank you for your respond, I solve the problem by following your advice.
